stages:
- lint
- test
lint:
  stage: lint
  image: "python:3.11"
  before_script:
    - python3.11 -m venv venv
  script:
    - venv/bin/tox -e lint
test:
  stage: test
  image: "python:3.11"
  before_script:
    - python3.11 -m venv venv
  script:
    - venv/bin/tox -e test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
